### ISSUE TITLE
Autocomplete Request Limit

### ISSUE THREAD

**Issue by tapizquent** [yshean/google_places_flutter#3]
More of an inquiry than an issue.

Since the autocomplete API is being hit on every single letter typed on the search, won't this eat up the request limit on the autocomplete API or rather get very expensive as the app scales?

Am I maybe not understanding how autocomplete works properly?

**Comment by yshean** [comment]
The use of session token will help to group the similar requests together (e.g. P, Pa, Par, Pari, Paris can be considered to be within the same session by a single user), but you should not use the same session token for every request fired by the app. The best practice is to generate a new token at the start of every search session (Google recommends using UUID v4).

When you supply the session token to each request, charges by session will apply, instead of by keystrokes - which can save you some cost

**Comment by tapizquent** [comment]
Thank you very much! I now understand a bit better the session token's job

**Comment by yshean** [comment]
Glad it helps! Closing the issue.
